# Generated by Django 3.0.5 on 2020-06-08 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subprogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subprogram', models.CharField(max_length=300)),
                ('program', models.ForeignKey(default='software', on_delete=django.db.models.deletion.SET_DEFAULT, to='myprojectdb.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=300)),
                ('subprogram', models.ForeignKey(default='front-end', on_delete=django.db.models.deletion.SET_DEFAULT, to='myprojectdb.Subprogram')),
            ],
        ),
    ]
